spring:
  application:
    name: user-service
  profiles:
    active: db
  datasource:
    url: ${url}
    name: ${username}
    password: ${password}
    driver-class-name: ${driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka