resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5 #?? ??? ? ??? ? ? ??
        wait-duration: 1000 # ?? ?? ??? ? ???(ms)

        retry-exceptions: # ? ??? rety ????.!
          - com.example.resilience.retry_training.exception.RetryException
        ignore-exceptions:
          - com.example.resilience.retry_training.exception.IgnoreException

    instances: #config class ?? ?? ?
      retryConfig:
        base-config: default #default ?? ???? ??!

  circuitbreaker:
    configs:
      default:
        sliding-window-type: count_based # ?? ??? ???? ???? opne ??? ??? ?, ???? vs ?? ??
        minimum-number-of-calls: 5 # ?? 5? ???? ???? ??? ??? opne?? ???? ??
        sliding-window-size: 10 # ?? ??? ?????? ? ??? ?? 10?? ??? ??? ??

        record-exceptions:
          - com.example.resilience.retry_training.exception.CircuitBreakerException
        ignore-exceptions:
          - com.example.resilience.retry_training.exception.IgnoreException

    instances:
      circuitBreakerConfig:
        base-config: default