server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/notcherry222/config_repository.git
          username: ENC(??? ???? ??? ??)
          password: ENC(???? ??)